name: Deploy app

on:
  push:
    branches:
      - "main"

jobs:
  build-bundle:
    name: Build bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Create or update .env file
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_APP_URL: ${{ secrets.VITE_APP_URL }}
          VITE_PUSHER_APP_ID: ${{ secrets.VITE_PUSHER_APP_ID }}
          VITE_PUSHER_APP_KEY: ${{ secrets.VITE_PUSHER_APP_KEY }}
          VITE_PUSHER_APP_SECRET: ${{ secrets.VITE_PUSHER_APP_SECRET }}
          VITE_PUSHER_APP_CLUSTER: ${{ secrets.VITE_PUSHER_APP_CLUSTER }}
          VITE_PUSHER_HOST: ${{ secrets.VITE_PUSHER_HOST }}
          VITE_PUSHER_PORT: ${{ secrets.VITE_PUSHER_PORT }}
          VITE_PUSHER_SSL: ${{ secrets.VITE_PUSHER_SSL }}
        run: |
          cd /var/www/dev-front-ss
          touch .env  # Создаем файл, если его нет
          
          # Функция для добавления или обновления переменной в .env
          set_env_var() {
            local var_name=$1
            local var_value=$2
            if grep -q "^${var_name}=" .env; then
              # Обновляем существующее значение
              sed -i "s|^${var_name}=.*|${var_name}=${var_value}|" .env
            else
              # Добавляем новое значение
              echo "${var_name}=${var_value}" >> .env
            fi
          }
          
          # Устанавливаем каждую переменную
          set_env_var "VITE_API_URL" "$VITE_API_URL"
          set_env_var "VITE_APP_URL" "$VITE_APP_URL"
          set_env_var "VITE_PUSHER_APP_ID" "$VITE_PUSHER_APP_ID"
          set_env_var "VITE_PUSHER_APP_KEY" "$VITE_PUSHER_APP_KEY"
          set_env_var "VITE_PUSHER_APP_SECRET" "$VITE_PUSHER_APP_SECRET"
          set_env_var "VITE_PUSHER_APP_CLUSTER" "$VITE_PUSHER_APP_CLUSTER"
          set_env_var "VITE_PUSHER_HOST" "$VITE_PUSHER_HOST"
          set_env_var "VITE_PUSHER_PORT" "$VITE_PUSHER_PORT"
          set_env_var "VITE_PUSHER_SSL" "$VITE_PUSHER_SSL"

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          password: ${{ secrets.DEV_SERVER_PASSWORD }}
          port: ${{ secrets.DEV_SERVER_PORT }}
          script: |
            cd /var/www/front-ss &&
            git pull origin dev &&
            yarn install &&
            yarn build
