name: Manual deploy app
run-name: Deploy "${{ inputs.branch_name }}" to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Branch name
        type: string
        required: true
      environment:
        description: Environment
        type: environment
        required: false
        default: development