name: Manual Deploy

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'
      environment:
        description: 'Deployment environment (e.g., production, staging)'
        required: true
        default: 'staging'